apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dynamic-operator
  template:
    metadata:
      labels:
        name: dynamic-operator
    spec:
      serviceAccountName: dynamic-operator
      containers:
        - name: dynamic-operator
          image: csharp-dynamic-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "information"
            - name: RETRY_MAX_ATTEMPTS
              value: "3"
            - name: RETRY_INITIAL_DELAY
              value: "5000"
            - name: RETRY_DELAY_MULTIPLIER
              value: "1.5"