apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.csharp-operator.example.com
spec:
  group: csharp-operator.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                desiredProperty:
                  type: integer
            status:
              type: object
              properties:
                actualProperty:
                  type: integer
      subresources:
        status: {}
  scope: Namespaced  
  names:
    plural: myresources
    singular: myresource
    kind: MyResource
    shortNames:
    - mr